version: '2'
services:
  jfg_notifier:
    build: .
    ports:
      - "${NOTIFIER_PORT_REST}:8080"
      - "${NOTIFIER_PORT_SOCKET}:${NOTIFIER_PORT_SOCKET}"
    volumes:
      - ./logs:/usr/local/tomcat/log
